#계정서버용 테스트

# POST http://localhost:27015/Register
# Content-Type: application/json

# {
#     "Id": "test456@naver.com",
#     "Password": "test456",
#     "ConfirmPassword": "test456"
# }


# POST http://localhost:27015/Login
# Content-Type: application/json

# {
#     "Id": "test1234@naver.com",
#     "Password": "test456"
# }

#게임서버용 테스트

# post http://localhost:27030/login
# content-type: application/json

# {
#     "id": "test123@naver.com",
#     "authtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAbmF2ZXIuY29tIiwibmJmIjoxNzI2ODYyMTk4LCJleHAiOjE3MjY4ODM3OTgsImlhdCI6MTcyNjg2MjE5OH0.G4GymhwBwqjP2r5UW1YqIq1Zp1XmyWYJDnuB6JT-uYo"
# }

post http://localhost:27030/CreateUser
content-type: application/json

{
    "Id": "test123@naver.com",
    "Nickname": "test1234",
    "Authtoken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAbmF2ZXIuY29tIiwibmJmIjoxNzI2ODYyMTk4LCJleHAiOjE3MjY4ODM3OTgsImlhdCI6MTcyNjg2MjE5OH0.G4GymhwBwqjP2r5UW1YqIq1Zp1XmyWYJDnuB6JT-uYo"
}
